server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: FIle
          uri: http://localhost:8081
          predicates:
            - Path=/files/**, 
        - id: Index
          uri: http://localhost:8082
          predicates:
            - Path=/indices/**, 
        - id: Steam
          uri: http://localhost:8083
          predicates:
            - Path=/steams/**, 
        - id: Dashboard
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: Notification
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: FIle
          uri: http://fIle:8080
          predicates:
            - Path=/files/**, 
        - id: Index
          uri: http://index:8080
          predicates:
            - Path=/indices/**, 
        - id: Steam
          uri: http://steam:8080
          predicates:
            - Path=/steams/**, 
        - id: Dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, 
        - id: Notification
          uri: http://notification:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
