---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: FIle
  labels:
    app: FIle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: FIle
  template:
    metadata:
      labels:
        app: FIle
    spec:
      containers:
        - name: FIle
          image: username/FIle:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Index
  labels:
    app: Index
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Index
  template:
    metadata:
      labels:
        app: Index
    spec:
      containers:
        - name: Index
          image: username/Index:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Steam
  labels:
    app: Steam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Steam
  template:
    metadata:
      labels:
        app: Steam
    spec:
      containers:
        - name: Steam
          image: username/Steam:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Dashboard
  labels:
    app: Dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Dashboard
  template:
    metadata:
      labels:
        app: Dashboard
    spec:
      containers:
        - name: Dashboard
          image: username/Dashboard:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Notification
  labels:
    app: Notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Notification
  template:
    metadata:
      labels:
        app: Notification
    spec:
      containers:
        - name: Notification
          image: username/Notification:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: FIle
  labels:
    app: FIle
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: FIle


---


apiVersion: v1
kind: Service
metadata:
  name: Index
  labels:
    app: Index
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Index


---


apiVersion: v1
kind: Service
metadata:
  name: Steam
  labels:
    app: Steam
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Steam


---


apiVersion: v1
kind: Service
metadata:
  name: Dashboard
  labels:
    app: Dashboard
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Dashboard


---


apiVersion: v1
kind: Service
metadata:
  name: Notification
  labels:
    app: Notification
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Notification

